---

- name: Download binary
  ansible.builtin.unarchive:
    src: https://github.com/jfolz/piproxy/releases/download/{{ piproxy_version }}/piproxy-linux-x86_64-v{{ piproxy_version }}.tar.xz
    dest: /usr/local/bin
    remote_src: yes
  become: true

- name: Create group 
  ansible.builtin.group:
    name: "{{ piproxy_group }}"
    system: true
  become: true
  when: piproxy_user != "root"

- name: Create user 
  ansible.builtin.user:
    name: "{{ piproxy_user }}"
    group: "{{ piproxy_group }}"
    system: true
    shell: /sbin/nologin
    create_home: no
    comment: "{{ piproxy_service_name }} service user"
  become: true
  when: piproxy_user != "root"

- name: Create config directory
  ansible.builtin.file:
    path: /etc/{{ piproxy_service_name }}
    owner: "{{ piproxy_user }}"
    group: "{{ piproxy_group }}"
    mode: 0700
    state: directory
  become: true

- name: Install config file
  ansible.builtin.template:
    src: templates/config.yml.j2
    dest: /etc/{{ piproxy_service_name }}/config.yml
    owner: "{{ piproxy_user }}"
    group: "{{ piproxy_group }}"
    mode: 0400
  become: true

- name: Create cache directory
  ansible.builtin.file:
    path: "{{ piproxy_cache_path }}"
    owner: "{{ piproxy_user }}"
    group: "{{ piproxy_group }}"
    mode: 0700
    state: directory
  become: true

- name: Install service file
  ansible.builtin.template:
    src: templates/piproxy.service.j2
    dest: /etc/systemd/system/{{ piproxy_service_name }}.service
  become: true

- name: Check service status
  command: systemctl is-active {{ piproxy_service_name }}
  register: service_status
  ignore_errors: true
  failed_when: false
  become: true

- name: Start service if it is not running
  ansible.builtin.systemd:
    name: "{{ piproxy_service_name }}"
    daemon_reload: true
    state: started
    enabled: true
  when: service_status.rc != 0
  become: true

- name: Reload service if it is running
  ansible.builtin.systemd:
    name: "{{ piproxy_service_name }}"
    daemon_reload: true
    state: reloaded
    enabled: true
  when: service_status.rc == 0
  become: true
