# molecule/default/Dockerfile.j2
FROM docker.io/library/ubuntu:22.04

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    systemd systemd-sysv sudo xz-utils python3 python3-pip

RUN rm -f /lib/systemd/system/systemd*udev* \
 && rm -f /lib/systemd/system/getty.target

CMD ["/sbin/init"]
