name: Molecule test

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  molecule-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install ansible molecule molecule-plugins[podman]
      - name: Run molecule test
        run: |
          molecule test
